# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# theme = "blowfish"  # Using Hugo Modules
baseURL = "https://skb.io"
defaultContentLanguage = "en"

# capitalizeListTitles = false
# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles
buildDrafts = false
buildFuture = false

enableEmoji = true

# SEO and Performance
enableGitInfo = true
enableMissingTranslationPlaceholders = false
hasCJKLanguage = true


# Hugo Modules configuration
[module]
[[module.imports]]
  path = "github.com/nunocoracao/blowfish/v2"

# Modern Hugo build settings
[build]
writeStats = true
useResourceCacheWhen = "fallback"

# Performance optimizations
[build.buildStats]
enable = true

# Asset processing
[params.assets]
disableFingerprinting = false
disableMinify = false

# Performance and caching
[params.performance]
enablePreload = true
enablePrefetch = true

# Custom assets
[params.custom]
# css = ["css/custom.css"]
# js = ["js/custom.js"]

# googleAnalytics = "G-PEDMYR1V0K"  # Will use environment variable

[imaging]
anchor = "Center"
resampleFilter = "Lanczos"
quality = 75
hint = "photo"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = 'always'
filename = 'sitemap.xml'
priority = 0.5


[related]
[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "series"
weight = 50

[[related.indices]]
name = "authors"
weight = 20

[[related.indices]]
name = "date"
weight = 10

[[related.indices]]
applyFilter = false
name = 'fragmentrefs'
type = 'fragments'
weight = 10
