languageCode = "en"
languageName = "English"
weight = 1
title = "skb.io"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logos/skb-logo.png"
  description = "Personal website and blog covering technology, projects, and ideas. Explore tutorials, project showcases, and technical insights."
  copyright = "Copy, _right?_ :thinking_face:"
  
  # SEO and Social Media
  [params.seo]
    image = "/img/logos/skb-logo.png"
    twitterCard = "summary_large_image"
    twitterSite = "@mpslanker"
    twitterCreator = "@mpslanker"
    
  # Open Graph
  [params.openGraph]
    image = "/img/logos/skb-logo.png"
    imageAlt = "SKB.io - Technology, Projects, and Ideas"
    siteName = "skb.io"
    type = "website"

# Site-wide author information (used for homepage, general attribution)
[params.author]
  name = "Matthew P. Slanker"
  email = "dev@msitp.com"
  image = "img/logos/skb-logo.png"
  imageQuality = 96
  headline = "I'm only human"
  bio = "A doer of doable things"
  links = [
    { email = "mailto:dev@msitp.com" },
    { github = "https://github.com/mpslanker" },
    { keybase = "https://keybase.io/mslanker" },
    { reddit = "https://reddit.com/user/mslanker" },
    { twitter = "https://twitter.com/mpslanker" }
  ]

