# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  # We have legit HTML in one of our articles
  # and need the following override.
  unsafe = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
