colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "posts" ]
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "/img/ripples.svg"
defaultFeaturedImage = "/img/cubes.png"
defaultBadgeImage = "img/skb-logo.png"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 12
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "img/ripples.svg"

[article]
showDate = true
showViews = false
showLikes = false
showDateUpdated = true
showAuthor = false
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = true
editURL = "https://github.dev/mpslanker/skb.io/"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true
showAuthorsBadges = true
showWordCount = true
sharingLinks = [ "linkedin", "twitter", "reddit", "facebook", "email" ]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showHero = true
heroStyle = "background"
showBreadcrumbs = true
# showTableOfContents = true
cardView = true

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showTableOfContents = true
groupByYear = false
cardView = true

[firebase]

[fathomAnalytics]

[buymeacoffee]
identifier = "mslanker"
globalWidget = true

[verification]
